version: 0.0
os: linux
files:
  - source: /wordpress
    destination: /var/www/html/wordpress
    overwrite: true
hooks:
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
file_exists_behavior: OVERWRITE 
