name: Deploy WordPress App

on:
  #workflow_dispatch: {}
  push:
    branches: [ main, develop, staging ]
  #pull_request:
  #  branches: [ main ]

env:
  applicationfolder: wordpress
  AWS_REGION: us-east-1
  S3BUCKET:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GITHUBOIDC_ROLE }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}
    - name: Run Deployment for main branch
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name CodeDeployWPApp --deployment-group-name CodeDeployWPAppGroup --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
    - name: Run Deployment for develop branch
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: |
        echo "Deploying branch ${{ github.ref }} to ${{ github.event.inputs.environment }}"
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name CodeDeployWPApp --deployment-group-name CodeDeployWPAppGroup --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
    - name: Run Deployment for staging branch
      if: ${{ github.ref == 'refs/heads/staging' }}
      run: |
        echo "Deploying branch ${{ github.ref }} to ${{ github.event.inputs.environment }}"
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name CodeDeployWPApp --deployment-group-name CodeDeployWPAppGroup --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
